package com.example.stomatology.app.core.firebase

object FirestoreCollections {
    const val APPOINTMENTS = "appointments"
    const val APPOINTMENT_SLOTS = "appointmentSlots"
    const val CLINICS = "clinics"
    const val DOCTOR_SCHEDULES = "doctorSchedules"
    const val HOLIDAYS = "holidays"
    const val STATUS_HISTORY = "statusHistory"
    const val USERS = "users"
}

object FirestoreFields {
    const val ADDRESS = "address"
    const val APPOINTMENT_IDS = "appointmentIds"
    const val ABOUT_DOCTOR = "aboutDoctor"
    const val BOOKED_COUNT = "bookedCount"
    const val CANCELLED_AT = "cancelledAt"
    const val CANCELLED_BY = "cancelledBy"
    const val CANCEL_REASON = "cancelReason"
    const val CAPACITY = "capacity"
    const val CAPACITY_PER_SLOT = "capacityPerSlot"
    const val CLINIC_ID = "clinicId"
    const val CLINIC_NAME = "clinicName"
    const val COMPLETED_AT = "completedAt"
    const val CREATED_AT = "createdAt"
    const val DATE = "date"
    const val DESCRIPTION = "description"
    const val DISPLAY_NAME = "displayName"
    const val DOCTOR_ID = "doctorId"
    const val DOCTOR_NAME = "doctorName"
    const val DURATION = "duration"
    const val EMAIL = "email"
    const val ENABLED = "enabled"
    const val END_TIME = "endTime"
    const val FIRST_NAME = "firstName"
    const val EXPERIENCE_YEARS = "experienceYears"
    const val ID = "id"
    const val IMAGE_URL = "imageUrl"
    const val LAST_NAME = "lastName"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val NAME = "name"
    const val PREVIOUS_DATE = "previousDate"
    const val PREVIOUS_TIME = "previousTime"
    const val PATIENT_ID = "patientId"
    const val PATIENT_NAME = "patientName"
    const val PATIENT_PHONE = "patientPhone"
    const val PHONE = "phone"
    const val PHOTO_URL = "photoUrl"
    const val PRICE_FROM = "priceFrom"
    const val PRICE_LIST = "priceList"
    const val RATING = "rating"
    const val REQUESTED_ROLE = "requestedRole"
    const val REQUEST_STATUS = "requestStatus"
    const val REVIEWS = "reviews"
    const val ROLE = "role"
    const val RESCHEDULED_FROM_ID = "rescheduledFromId"
    const val SLOT_DURATION_MIN = "slotDurationMin"
    const val START_TIME = "startTime"
    const val SERVICES = "services"
    const val SERVICE = "service"
    const val SPECIALTY = "specialty"
    const val STATUS = "status"
    const val STATUS_CHANGED_BY = "statusChangedBy"
    const val STATUS_HISTORY_AT = "at"
    const val STATUS_HISTORY_BY = "by"
    const val STATUS_HISTORY_FROM = "from"
    const val STATUS_HISTORY_REASON = "reason"
    const val STATUS_HISTORY_TO = "to"
    const val TIME = "time"
    const val WORKING_DAYS = "workingDays"
    const val BREAKS = "breaks"
    const val DAY_OF_WEEK = "dayOfWeek"
    const val UID = "uid"
    const val UPDATED_AT = "updatedAt"
}

object UserRoles {
    const val ADMIN = "admin"
    const val DOCTOR = "doctor"
    const val PATIENT = "patient"
}

object RoleRequestStatus {
    const val APPROVED = "approved"
    const val NONE = "none"
    const val PENDING = "pending"
    const val REJECTED = "rejected"
}
